[package]
name = "erl_tokenize"
version = "0.2.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "Erlang source code tokenizer"
homepage = "https://github.com/sile/erl_tokenize"
repository = "https://github.com/sile/erl_tokenize"
readme = "README.md"
keywords = ["erlang", "tokenizer", "lexer"]
categories = ["parser-implementations"]
license = "MIT"

[badges]
travis-ci = {repository = "sile/erl_tokenize"}

[dependencies]
num = "0.1"
trackable = "0.1"

[dev-dependencies]
clap = "2"